spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/makaranda}
    username: ${DATABASE_USER:makaranda}
    password: ${DATABASE_PASSWORD:makaranda}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
